name: default
env:
  CGO_ENABLED: 0
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  gotest:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go test -mod=vendor -v ./...
  goreleaser:
    name: release
    runs-on: ubuntu-latest
    needs:
      - gotest
      - golangci
    steps:
      - uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fetch-depth: 0
      - uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
